<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Calcul" nsURI="http://calcul" nsPrefix="calcul">
  <eClassifiers xsi:type="ecore:EClass" name="Calcul">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true" eOpposite="#//Expression/calcul"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entrees" upperBound="-1"
        eType="#//Entree" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantes" upperBound="-1"
        eType="#//Constante" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sorties" upperBound="-1"
        eType="#//Sortie" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calcul" lowerBound="1"
        eType="#//Calcul" eOpposite="#//Calcul/expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binaire" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gauche" lowerBound="1"
        eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="droite" lowerBound="1"
        eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryType" lowerBound="1"
        eType="#//BinaryTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultat" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unaire" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valeur" lowerBound="1"
        eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unaireType" lowerBound="1"
        eType="#//UnaireType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultat" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constante">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sortie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Val" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entree" eType="#//Entree"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="const" eType="#//Constante"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortie" eType="#//Sortie"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryTypes">
    <eLiterals name="Addition"/>
    <eLiterals name="Soustraction" value="1"/>
    <eLiterals name="Division" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaireType">
    <eLiterals name="sin"/>
    <eLiterals name="cos" value="1"/>
    <eLiterals name="Opposee" value="2"/>
  </eClassifiers>
</ecore:EPackage>
